create table checkout (id bigint generated by default as identity, date date, expiration_date date, journal_id bigint not null, result varchar(255), primary key (id))
create table fleet (id bigint generated by default as identity, name varchar(255), primary key (id))
create table insurance (id bigint generated by default as identity, name varchar(255), end_date date, journal_id bigint not null, start_date date, primary key (id))
create table journal (id bigint generated by default as identity, vehicle_id bigint not null, primary key (id))
create table repair (id bigint generated by default as identity, cost double not null, date date, description varchar(255), journal_id bigint not null, primary key (id))
create table users (id bigint generated by default as identity, enabled boolean not null, login varchar(255), password varchar(255), role varchar(255), primary key (id))
create table vehicle (id bigint generated by default as identity, manufacturer varchar(255), model varchar(255), production_year integer not null, fleet_id bigint not null, local bigint not null, primary key (id))
alter table users add constraint UK_ow0gan20590jrb00upg3va2fn unique (login)
alter table checkout add constraint FK16q77io1wgvifhig2q9xtdpxp foreign key (journal_id) references journal
alter table insurance add constraint FKp7k62j4xnxbo96bva1l7vfmx foreign key (journal_id) references journal
alter table journal add constraint FKsw6k8i4bv17stm9480vsfcokp foreign key (vehicle_id) references vehicle
alter table repair add constraint FKk2u7505o799y8t9yuja7l9ik4 foreign key (journal_id) references journal
alter table vehicle add constraint FKpwc6m3cb1dafsak3w7i6wrxqi foreign key (fleet_id) references fleet
